version: '3.4'

services:
  matp:
    image: node:16-slim #matp
    build: .
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    volumes:
      - .:/app
    links:
      - mongodb
  mongodb: 
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - data:/data/db

  keycloak:
    image: jboss/keycloak
    ports: 
      - 8080:8080
    environment:  
      DB_VENDOR: MYSQL 
      DB_ADDR: keycloak-db
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
      KEYCLOAK_LOGLEVEL: DEBUG
    depends_on:
      - keycloak-db
  keycloak-db:
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password

  adminer:
    image: adminer
    restart: always
    ports:
      - 8083:8080


volumes:
  data:
  mysql_data: